[tool.poetry]
name = "llm-engineering-course"
version = "0.1.0"
description = "Environment setup for the Advanced LLM Engineering Course"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

# Core Libraries - CUDA 12.1 optimized
datasets = ">=2.14.0"
accelerate = ">=0.24.0"

# Distributed Training

# Inference & Serving
# CUDA 11.5 compatible versions
fastapi = ">=0.104.0"
uvicorn = ">=0.24.0"

# Compression & Quantization - CUDA 12.1 compatible

# Evaluation

# Data & Utility
numpy = ">=1.24.0"
pandas = ">=2.0.0"
scikit-learn = ">=1.3.0"

# CUDA utilities

# Flash Attention (CUDA 12.1 compatible)
jupyterlab = "^4.4.9"
ipywidgets = "^8.1.7"
matplotlib = "^3.10.6"
seaborn = "^0.13.2"
tqdm = "^4.67.1"
torch = {version = "^2.5.1", source = "pytorch-cu121"}
torchvision = {version = "^0.20.1", source = "pytorch-cu121"}
torchaudio = {version = "^2.5.1", source = "pytorch-cu121"}
transformers = "^4.57.0"

[tool.poetry.extras]
inference = ["vllm"]
flash-attention = ["flash-attn"]
all = ["vllm", "flash-attn"]

[[tool.poetry.source]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
